"""update bus model

Revision ID: 3f253eab0847
Revises: c646180eeac2
Create Date: 2026-02-19 13:21:52.760000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f253eab0847'
down_revision: Union[str, Sequence[str], None] = 'c646180eeac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buses', 'route_variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('route_variant', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
