"""update bus model

Revision ID: c646180eeac2
Revises: 5fbd71ccd4ad
Create Date: 2026-02-18 19:30:06.572318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c646180eeac2'
down_revision: Union[str, Sequence[str], None] = '5fbd71ccd4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('route_variant', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buses', 'route_variant')
    # ### end Alembic commands ###
